language: ruby

sudo:
    false
    
rvm:
  - 2.7
  - 2.6
  - 2.5

matrix:
    allow_failures:
    - rvm: 2.7

install:
  - gem install cybersource_rest_client


script: 
  - bash sample_code_runner.sh
  - cat output.log
